// Verified content shared by indexable pages and inert modal templates.
export const projects = [
  {
    id: 'kicord', slug: 'kicord', number: '01', title: 'KiCord',
    category: 'Ecosistema Discord', status: 'Código cerrado',
    summary: 'Un ecosistema propio alrededor de Discord: cliente de código cerrado, web y bot.',
    role: 'Desarrollo del cliente, web y bot',
    overview: 'KiCord es un cliente modificado de Discord de código cerrado. Mi participación abarca el cliente, la web y el bot de KiCord; el cliente se centra en personalización y plugins. Los plugins relacionados no convierten el cliente KiCord en open source.',
    approach: 'Desarrollar y mantener opciones de personalización, integración de plugins y mejoras de interfaz. KiCord no es un producto oficial de Discord.',
    tags: ['Discord', 'Personalización', 'Plugins', 'UX'],
    links: [{ label: 'Visitar KiCord', url: 'https://www.kicord.es/es' }],
    phone: 'kicord', next: 'portfolio',
    details: [
      { title: 'Cliente', text: 'Desarrollo y personalización de un cliente modificado de Discord de código cerrado.' },
      { title: 'Web', text: 'Desarrollo de la presencia web del proyecto; el sitio público utiliza Next.js.' },
      { title: 'Bot', text: 'Desarrollo del bot como parte del ecosistema KiCord.' },
    ],
  },
  {
    id: 'papige', slug: 'portfolio', number: '02', title: 'PabloSchefer.com',
    category: 'Portfolio personal', status: 'Esta misma web',
    summary: 'Esta misma web: HTML, CSS y JavaScript, animaciones GSAP y funciones de Vercel.',
    role: 'Diseño, desarrollo y mantenimiento',
    overview: 'PabloSchefer.com es esta misma web, mantenida en Web-CV. Presenta proyectos, experiencia y contacto mediante HTML estático, CSS y JavaScript. GSAP aporta movimiento; pequeñas funciones de Vercel gestionan la actividad de GitHub y el contacto.',
    approach: 'Una identidad editorial con mejora progresiva: contenido accesible sin JavaScript, imágenes adaptables y estados de contacto que distinguen un borrador de un envío aceptado.',
    tags: ['HTML', 'CSS', 'JavaScript', 'GSAP', 'Vercel'],
    links: [{ label: 'Ver código de la web', url: 'https://github.com/PapiGECode/Web-CV' }],
    phone: 'portfolio', next: 'kernelos',
    details: [
      { title: 'Contenido indexable', text: 'Páginas estáticas de proyecto y navegación útil sin depender de una aplicación React.' },
      { title: 'Accesibilidad y movimiento', text: 'Pruebas de teclado, temas, tamaños de pantalla y preferencias de movimiento.' },
      { title: 'Contacto transparente', text: 'La interfaz distingue entre preparar un correo y la entrega aceptada por el proveedor.' },
    ],
  },
  {
    id: 'kernelos', slug: 'kernelos', number: '03', title: 'KernelOS',
    category: 'ISO personalizada de Windows', status: 'Colaboración en soporte',
    summary: 'ISO personalizada de Windows orientada a gaming. Mi contribución está en soporte técnico y comunidad.',
    role: 'Soporte técnico y comunidad',
    overview: 'KernelOS es una ISO personalizada de Windows orientada a gaming. Aquí aparece como una colaboración en soporte técnico y comunidad, no como un sistema operativo creado por mí.',
    approach: 'Ayudar con incidencias, orientar a usuarios y trasladar problemas recurrentes. Esta labor de soporte es distinta de la autoría y del desarrollo de la ISO.',
    tags: ['Windows', 'Diagnóstico', 'Soporte', 'Comunidad'],
    links: [{ label: 'Visitar KernelOS', url: 'https://kernelos.org/' }],
    phone: 'kernelos', next: 'kicord',
    details: [
      { title: 'Diagnóstico', text: 'Orientación sobre configuración, controladores y compatibilidad.' },
      { title: 'Comunidad', text: 'Ayuda a usuarios y organización de consultas técnicas.' },
      { title: 'Feedback técnico', text: 'Comunicación de problemas reproducibles y necesidades recurrentes.' },
    ],
  },
  {
    id: 'thiagoiutu', slug: 'thiagoiutu', number: '04', title: 'ThiagoIUTU',
    category: 'Web de creador', status: 'Desarrollo web',
    summary: 'Un espacio para el archivo, el presente y la comunidad de ThiagoIUTU.',
    role: 'Desarrollo de la web',
    overview: 'Una web dedicada a ThiagoIUTU que reúne su universo como creador y su comunidad en un mismo lugar.',
    approach: 'Mi participación está en el desarrollo de la web. El trabajo se presenta como proyecto web, diferenciándolo del bot de la comunidad.',
    tags: ['Web', 'Creador', 'Comunidad'],
    links: [{ label: 'Visitar ThiagoIUTU', url: 'https://thiagoiutu.com/' }],
    next: 'robleis',
    details: [
      { title: 'Identidad del creador', text: 'Un espacio propio dedicado al universo de ThiagoIUTU.' },
      { title: 'Archivo y presente', text: 'Contenido y comunidad como punto de encuentro de la web.' },
    ],
  },
  {
    id: 'robleis', slug: 'robleis', number: '05', title: 'Robleis',
    category: 'Proyecto web', status: 'Desarrollo web',
    summary: 'Un proyecto web dedicado al universo de Robleis.',
    role: 'Desarrollo del proyecto web',
    overview: 'Proyecto de desarrollo web centrado en Robleis. Forma parte de mi trabajo con experiencias digitales dedicadas a creadores y artistas.',
    approach: 'Trabajo en el proyecto web y su presentación digital. Esta ficha no implica una vinculación oficial con el artista.',
    tags: ['Web', 'Música', 'Identidad'], links: [], next: 'thiago-community',
    details: [{ title: 'Enfoque', text: 'Una experiencia web que toma a Robleis como tema central, no una plantilla de portfolio personal.' }],
  },
  {
    id: 'thiago-community', slug: 'thiago-community', number: '06', title: 'Thiago Community',
    category: 'Bot de comunidad', status: 'Desarrollo de bot',
    summary: 'El proyecto de bot para la comunidad de ThiagoIUTU.',
    role: 'Desarrollo del bot',
    overview: 'Thiago Community es un proyecto de bot para la comunidad de ThiagoIUTU. Se presenta como un trabajo independiente de su web.',
    approach: 'Mi participación se centra en el desarrollo de este bot y su contexto comunitario.',
    tags: ['Bot', 'Comunidad'], links: [], next: 'papigegamer-web',
    details: [{ title: 'Proyecto independiente', text: 'La web de ThiagoIUTU y el bot de su comunidad son trabajos diferentes dentro del mismo entorno.' }],
  },
  {
    id: 'papigegamer-web', slug: 'papigegamer-web', number: '07', title: 'PapiGECode',
    category: 'Laboratorio personal', status: 'PapiGEGamer.com',
    summary: 'Mi espacio de software, proyectos y experimentos en PapiGEGamer.com.',
    role: 'Desarrollo del laboratorio web',
    overview: 'PapiGEGamer.com es mi laboratorio PapiGECode: un espacio para software y experimentos. Es una web distinta de este portfolio profesional, PabloSchefer.com.',
    approach: 'Separar el espacio de exploración personal de la presentación profesional, manteniendo una identidad propia para cada proyecto.',
    tags: ['Next.js', 'Software', 'Experimentación'],
    links: [{ label: 'Visitar PapiGEGamer.com', url: 'https://papigegamer.com/' }],
    next: 'kicord',
    details: [
      { title: 'Laboratorio', text: 'Un espacio personal de proyectos de software y experimentación.' },
      { title: 'Web independiente', text: 'Su sitio público utiliza Next.js; no es la implementación de PabloSchefer.com.' },
    ],
  },
];
